"""
Re-download the self-hosted fonts and rewrite apps/web/src/fonts.css.

    python3 tools/fonts/fetch-fonts.py

Run it to pick up an upstream font revision, or to add a subset after adding a
language. Nothing about it runs at build time — the files it writes are what
ship, and they are committed.

Why self-hosted at all: a <link> to fonts.googleapis.com tells a third party
which pages a reader opens, and the app declines that trade elsewhere (the
video player fetches nothing from YouTube until it is clicked). 106 KB against
a 1.1 MB model is a proportionate price for not making that request.

Why variable fonts: the site uses weights 400, 500, 600 and the browser's 700
for headings. Three static cuts per family would be three files and more bytes
than one variable file that covers the whole range.

Why these subsets: Google splits each family by script, and the browser
downloads only the ones a page actually needs, keyed by unicode-range. Space
Grotesk has no Cyrillic, so Russian sans text falls back per glyph. JetBrains
Mono does have it, and carries the translated panel headings. Greek and
Vietnamese are dropped because neither is among the ten languages. Japanese and
Chinese are in neither face and fall back to the system, which is correct — a
CJK webfont is megabytes, and every device already has one.
"""
import pathlib
import re
import urllib.request

HERE = pathlib.Path(__file__).resolve().parents[2]
FONT_DIR = HERE / "apps/web/src/assets/fonts"
CSS_OUT = HERE / "apps/web/src/fonts.css"

API = ("https://fonts.googleapis.com/css2"
       "?family=Space+Grotesk:wght@300..700"
       "&family=JetBrains+Mono:wght@100..800&display=swap")

# A modern browser UA is required: Google serves .ttf to anything it doesn't
# recognise, and woff2 is both smaller and universally supported now.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

KEEP = {
    "Space Grotesk": {"latin", "latin-ext"},
    "JetBrains Mono": {"latin", "latin-ext", "cyrillic"},
}

HEADER = """/* Self-hosted type.
 *
 * Both faces are SIL Open Font License 1.1 (see assets/fonts/OFL-*.txt), which
 * permits bundling with the licence included. Self-hosted rather than linked
 * from Google's CDN: a webfont link tells a third party which pages a reader
 * opens, and the app already refuses that trade elsewhere — the video player
 * fetches nothing from YouTube until it is clicked.
 *
 * Variable fonts, one file per subset, each covering every weight the site uses
 * (400, 500, 600, and the browser's 700 for headings) in a single download.
 *
 * font-display: swap — text is readable in the fallback from the first paint
 * and reflows when the face arrives, rather than being invisible while it
 * loads.
 *
 * Generated by tools/fonts/fetch-fonts.py. Edit that, not this.
 */"""


def fetch(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60).read()


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(API).decode("utf-8")
    blocks = re.findall(r"/\* ([\w-]+) \*/\s*@font-face \{(.*?)\}", css, re.S)

    out, total = [HEADER], 0
    for subset, body in blocks:
        family = re.search(r"font-family: '([^']+)'", body).group(1)
        if subset not in KEEP.get(family, set()):
            continue
        url = re.search(r"url\((https://[^)]+)\)", body).group(1)
        weight = re.search(r"font-weight: ([\d ]+);", body).group(1).strip()
        urange = re.search(r"unicode-range: ([^;]+);", body).group(1).strip()

        name = f"{family.lower().replace(' ', '-')}-{subset}.woff2"
        data = fetch(url)
        (FONT_DIR / name).write_bytes(data)
        total += len(data)
        print(f"  {name:<36} {len(data) / 1024:6.1f} KB")

        out.append(f"""/* {subset} */
@font-face {{
  font-family: '{family}';
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: url('./assets/fonts/{name}') format('woff2');
  unicode-range: {urange};
}}""")

    if len(out) == 1:
        raise SystemExit("no faces matched KEEP — did the upstream subset names change?")
    CSS_OUT.write_text("\n".join(out) + "\n")
    print(f"\n{len(out) - 1} files, {total / 1024:.0f} KB, wrote {CSS_OUT.name}")


if __name__ == "__main__":
    main()
